---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-node
  namespace: todonodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-node
  template:
    metadata:
      labels:
        app: mysql-node
    spec:
      containers:
      - image: registry.redhat.io/rhel8/mysql-80:1-156
        name: mysql-node
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_DATABASE
          value: items
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: db-volume
      volumes:
      - name: db-volume
        emptyDir: {}
      - name: db-init
        emptyDir: {}